// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class MaryCarmenDBContext : DbContext
{
    public MaryCarmenDBContext()
    {
    }

    public MaryCarmenDBContext(DbContextOptions<MaryCarmenDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<categoria> categoria { get; set; }

    public virtual DbSet<detalle_traslado> detalle_traslado { get; set; }

    public virtual DbSet<detalle_venta> detalle_venta { get; set; }

    public virtual DbSet<productos> productos { get; set; }

    public virtual DbSet<roles> roles { get; set; }

    public virtual DbSet<sucursales> sucursales { get; set; }

    public virtual DbSet<traslados_internos> traslados_internos { get; set; }

    public virtual DbSet<usuarios> usuarios { get; set; }

    public virtual DbSet<ventas> ventas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-05HME1I;Initial Catalog=MaryCarmenBD;Integrated Security=True;Encrypt=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<categoria>(entity =>
        {
            entity.HasKey(e => e.id_categoria).HasName("PK__categori__CD54BC5AC0EB526E");

            entity.HasIndex(e => e.nombre_categoria, "UQ__categori__4EBF625915E1108E").IsUnique();

            entity.Property(e => e.nombre_categoria)
                .IsRequired()
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.tipo_categoria)
                .HasMaxLength(45)
                .IsUnicode(false);
        });

        modelBuilder.Entity<detalle_traslado>(entity =>
        {
            entity.HasKey(e => e.id_detalle_traslado).HasName("PK__detalle___B6CC495515DF2568");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.detalle_traslado)
                .HasForeignKey(d => d.id_producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_t__id_pr__5165187F");

            entity.HasOne(d => d.id_trasladoNavigation).WithMany(p => p.detalle_traslado)
                .HasForeignKey(d => d.id_traslado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_t__id_tr__52593CB8");
        });

        modelBuilder.Entity<detalle_venta>(entity =>
        {
            entity.HasKey(e => e.id_detalle_venta).HasName("PK__detalle___5B265D47EF5901AB");

            entity.Property(e => e.precio_unitario_venta).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.subtotal).HasColumnType("decimal(15, 2)");

            entity.HasOne(d => d.id_productoNavigation).WithMany(p => p.detalle_venta)
                .HasForeignKey(d => d.id_producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_v__id_pr__534D60F1");

            entity.HasOne(d => d.id_ventaNavigation).WithMany(p => p.detalle_venta)
                .HasForeignKey(d => d.id_venta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__detalle_v__id_ve__5441852A");
        });

        modelBuilder.Entity<productos>(entity =>
        {
            entity.HasKey(e => e.id_producto).HasName("PK__producto__FF341C0D20AC981D");

            entity.HasIndex(e => e.codigo_producto, "UQ__producto__105107A8F8F6C038").IsUnique();

            entity.Property(e => e.categoria)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.codigo_producto)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.nombre_producto)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.precio_referencia).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.id_categoriaNavigation).WithMany(p => p.productos)
                .HasForeignKey(d => d.id_categoria)
                .HasConstraintName("FK__productos__id_ca__5535A963");
        });

        modelBuilder.Entity<roles>(entity =>
        {
            entity.HasKey(e => e.id_rol).HasName("PK__roles__6ABCB5E0F5B0B3A3");

            entity.HasIndex(e => e.nombre_rol, "UQ__roles__673CB435F47B497B").IsUnique();

            entity.Property(e => e.nombre_rol)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<sucursales>(entity =>
        {
            entity.HasKey(e => e.id_sucursal).HasName("PK__sucursal__4C758013B6FC8643");

            entity.HasIndex(e => e.nombre_sucursal, "UQ__sucursal__D3D361CAEF28EACA").IsUnique();

            entity.Property(e => e.direccion)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.estado)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("activa");
            entity.Property(e => e.nombre_sucursal)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.telefono)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<traslados_internos>(entity =>
        {
            entity.HasKey(e => e.id_traslado).HasName("PK__traslado__3E65EDDDC69AEE73");

            entity.Property(e => e.estado)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("pendiente");
            entity.Property(e => e.fecha_hora_envio).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.id_sucursal_destinoNavigation).WithMany(p => p.traslados_internos)
                .HasForeignKey(d => d.id_sucursal_destino)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__traslados__id_su__5629CD9C");

            entity.HasOne(d => d.id_usuario_recibeNavigation).WithMany(p => p.traslados_internos)
                .HasForeignKey(d => d.id_usuario_recibe)
                .HasConstraintName("FK__traslados__id_us__571DF1D5");
        });

        modelBuilder.Entity<usuarios>(entity =>
        {
            entity.HasKey(e => e.id_usuario).HasName("PK__usuarios__4E3E04AD15629DCC");

            entity.HasIndex(e => e.nombre_usuario, "UQ__usuarios__D4D22D7464596566").IsUnique();

            entity.Property(e => e.estado)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasDefaultValue("activo");
            entity.Property(e => e.nombre_completo)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.nombre_usuario)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.password_hash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.id_rolNavigation).WithMany(p => p.usuarios)
                .HasForeignKey(d => d.id_rol)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__usuarios__id_rol__5812160E");

            entity.HasOne(d => d.id_sucursalNavigation).WithMany(p => p.usuarios)
                .HasForeignKey(d => d.id_sucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__usuarios__id_suc__59063A47");
        });

        modelBuilder.Entity<ventas>(entity =>
        {
            entity.HasKey(e => e.id_venta).HasName("PK__ventas__459533BF8FF1BEBE");

            entity.HasIndex(e => e.numero_factura_o_recibo, "UQ__ventas__B68D0074E2AE1113").IsUnique();

            entity.Property(e => e.fecha_hora_venta).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.metodo_pago)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.numero_factura_o_recibo)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.total_venta).HasColumnType("decimal(15, 2)");

            entity.HasOne(d => d.id_sucursalNavigation).WithMany(p => p.ventas)
                .HasForeignKey(d => d.id_sucursal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ventas__id_sucur__59FA5E80");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}