// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class categoria
{
    public int id_categoria { get; set; }

    public string nombre_categoria { get; set; }

    public string tipo_categoria { get; set; }
    [JsonIgnore]
    public virtual ICollection<productos> productos { get; set; } = new List<productos>();
}