// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class detalle_venta
{
    public int id_detalle_venta { get; set; }

    public int id_venta { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }

    public decimal precio_unitario_venta { get; set; }

    public decimal subtotal { get; set; }
    [JsonIgnore]
    public virtual productos id_productoNavigation { get; set; }
    [JsonIgnore]
    public virtual ventas id_ventaNavigation { get; set; }
}