// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class detalle_traslado
{
    public int id_detalle_traslado { get; set; }

    public int id_traslado { get; set; }

    public int id_producto { get; set; }

    public int cantidad { get; set; }
    [JsonIgnore]
    public virtual productos id_productoNavigation { get; set; }
    [JsonIgnore]
    public virtual traslados_internos id_trasladoNavigation { get; set; }
}