// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class productos
{
    public int id_producto { get; set; }

    public string nombre_producto { get; set; }

    public string descripcion { get; set; }

    public decimal precio_referencia { get; set; }

    public string codigo_producto { get; set; }

    public string categoria { get; set; }

    public int? id_categoria { get; set; }
    [JsonIgnore]
    public virtual ICollection<detalle_traslado> detalle_traslado { get; set; } = new List<detalle_traslado>();
    [JsonIgnore]
    public virtual ICollection<detalle_venta> detalle_venta { get; set; } = new List<detalle_venta>();
    [JsonIgnore]
    public virtual categoria id_categoriaNavigation { get; set; }
}