// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class roles
{
    public int id_rol { get; set; }

    public string nombre_rol { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<usuarios> usuarios { get; set; } = new List<usuarios>();
}