// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class sucursales
{
    public int id_sucursal { get; set; }

    public string nombre_sucursal { get; set; }

    public string direccion { get; set; }

    public string telefono { get; set; }

    public string estado { get; set; }

    public virtual ICollection<traslados_internos> traslados_internos { get; set; } = new List<traslados_internos>();

    public virtual ICollection<usuarios> usuarios { get; set; } = new List<usuarios>();

    public virtual ICollection<ventas> ventas { get; set; } = new List<ventas>();
}