// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class traslados_internos
{
    public int id_traslado { get; set; }

    public DateOnly fecha_hora_envio { get; set; }

    public DateOnly? fecha_hora_recepcion { get; set; }

    public int id_sucursal_origen { get; set; }

    public int id_sucursal_destino { get; set; }

    public string estado { get; set; }

    public int? id_usuario_recibe { get; set; }

    public virtual ICollection<detalle_traslado> detalle_traslado { get; set; } = new List<detalle_traslado>();

    public virtual sucursales id_sucursal_destinoNavigation { get; set; }

    public virtual usuarios id_usuario_recibeNavigation { get; set; }
}