// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class usuarios
{
    public int id_usuario { get; set; }

    public string nombre_usuario { get; set; }

    public string password_hash { get; set; }

    public string nombre_completo { get; set; }

    public int id_rol { get; set; }

    public int id_sucursal { get; set; }

    public string estado { get; set; }
    [JsonIgnore]
    public virtual roles id_rolNavigation { get; set; }
    [JsonIgnore]
    public virtual sucursales id_sucursalNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<traslados_internos> traslados_internos { get; set; } = new List<traslados_internos>();
}