// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MariaCarmen.Infraestructura.AccesoDatos;

public partial class ventas
{
    public int id_venta { get; set; }

    public string numero_factura_o_recibo { get; set; }

    public DateOnly fecha_hora_venta { get; set; }

    public decimal total_venta { get; set; }

    public int id_usuario_vendedor { get; set; }

    public int id_sucursal { get; set; }

    public string metodo_pago { get; set; }

    public virtual ICollection<detalle_venta> detalle_venta { get; set; } = new List<detalle_venta>();

    public virtual sucursales id_sucursalNavigation { get; set; }
}